WAZZUP
================

```{r}
words <- readLines(url("http://dtkaplan.github.io/ScientificComputing/Syllabus/Daily/Day-07/word_list_moby_crossword-flat/word_list_moby_crossword.flat.txt"))

length(words)
head (words)

```

```{r}
findScrabble<-function(letters){
  words<-words[grep(letters[1],words)]
  words<-words[grep(letters[2],words)]
  words<-words[grep(letters[3],words)]
  return(words)
  }
length(findScrabble(c("b","n","r")))
```

```{r}
findScrabble2<-function(letters){
  for(k in 1:length(letters)){
  words<-words[grep(letters[k],words)]
  if(length(words) < 10) break
  }
return(words)
}
```

```{r}
findScrabble2(c("b","n","r","x","q"))
```

## Fibonaccci Sequence:
```{r}
fibSeq<-function(n){
  current<-1
  beforeIt<-0
  for(k in 1:n){
    tmp<-current+beforeIt
    beforeIt<-current
    current<-tmp
    }
  return(current)
  }
```

```{r}
fibSeq(5)
fibSeq(8)
```

```{r}
fib<-function(n){
  if( n < 0 | floor(n) !=n) {
    warning("youre dumb")
    return(NA)
    }
  sofar=c(0,1)
  for (k in 3:n) {
    sofar[k] <- sofar[k-1] + sofar[k-2]
    }
  return(sofar)
  }
fib(7)
```

## Prime Numbers
```{r}
guess<- rep(TRUE,100)
for (k in 2:100)
    guess[(1:100) %%k==0 & (1:100)>k]<-FALSE

```

```{r}
primeSieve<- function(n){
  guess <- rep(TRUE,n)
  inds <- 1:n
  for (k in 2:n){
    if(guess[k]){
      }
    guess[ (inds%%k)==0 & inds > k] <- FALSE
  }
return(which(guess))
}

primeSieve(1000)